# Generated by Django 5.2.12 on 2026-06-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='活动标题')),
                ('university', models.CharField(max_length=200, verbose_name='高校名称')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='活动日期')),
                ('event_end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('location', models.CharField(blank=True, default='', max_length=300, verbose_name='活动地点')),
                ('description', models.TextField(blank=True, default='', verbose_name='活动描述')),
                ('source_url', models.URLField(max_length=500, unique=True, verbose_name='来源链接')),
                ('source_name', models.CharField(blank=True, default='', max_length=100, verbose_name='来源平台')),
                ('contact_email', models.CharField(blank=True, default='', max_length=200, verbose_name='联系人邮箱')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='联系人电话')),
                ('category', models.CharField(choices=[('AI', 'AI'), ('Web3', 'Web3'), ('AI+Web3', 'AI+Web3')], default='AI', max_length=20, verbose_name='活动分类')),
                ('event_type', models.CharField(choices=[('讲座', '讲座'), ('黑客松', '黑客松'), ('论坛', '论坛'), ('工作坊', '工作坊'), ('其他', '其他')], default='其他', max_length=20, verbose_name='活动类型')),
                ('registration_url', models.URLField(blank=True, default='', max_length=500, verbose_name='报名链接')),
                ('is_contacted', models.BooleanField(default=False, verbose_name='是否已联系')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='匹配度评分')),
                ('raw_data', models.TextField(blank=True, default='', verbose_name='原始数据 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': '高校活动',
                'verbose_name_plural': '高校活动',
                'ordering': ['-created_at'],
            },
        ),
    ]
