# Generated by Django 5.2.12 on 2026-07-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('summary', models.TextField(blank=True, default='', verbose_name='AI 摘要')),
                ('source_type', models.CharField(choices=[('manual', '手动提交'), ('twitter', 'Twitter')], default='manual', max_length=20, verbose_name='来源类型')),
                ('source_url', models.URLField(blank=True, default='', max_length=500, verbose_name='来源链接')),
                ('tweet_id', models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='推文ID（去重键）')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': '活动回顾',
                'verbose_name_plural': '活动回顾',
                'ordering': ['-created_at'],
            },
        ),
    ]
