# Generated by Django 5.2.12 on 2026-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_eventreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50, unique=True, verbose_name='推文 ID')),
                ('text', models.TextField(verbose_name='原始文案')),
                ('text_processed', models.TextField(blank=True, default='', verbose_name='AI 润色后文案')),
                ('media_urls', models.TextField(blank=True, default='[]', verbose_name='图片 URL 列表 (JSON)')),
                ('twitter_url', models.URLField(max_length=500, verbose_name='推文链接')),
                ('summary', models.TextField(blank=True, default='', verbose_name='AI 摘要')),
                ('is_review_worthy', models.BooleanField(default=False, verbose_name='是否高校行相关')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='是否含敏感文案')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='推文发布时间')),
                ('raw_data', models.TextField(blank=True, default='', verbose_name='原始 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
            ],
            options={
                'verbose_name': '推文回顾',
                'verbose_name_plural': '推文回顾',
                'ordering': ['-published_at'],
            },
        ),
    ]
