# Generated by Django 5.2.12 on 2026-07-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_workspace_reference_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetreview',
            name='space_summary',
            field=models.TextField(blank=True, default='', verbose_name='Space 语音总结'),
        ),
        migrations.AddField(
            model_name='tweetreview',
            name='space_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Space 语音链接'),
        ),
    ]
