# Generated by Django 5.2.16 on 2026-07-10 18:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def backfill_legacy_event_contacts(apps, schema_editor):
    UniversityEvent = apps.get_model('home', 'UniversityEvent')
    ContactPoint = apps.get_model('home', 'ContactPoint')
    field_channels = (
        ('contact_email', 'email'),
        ('contact_ai_email', 'email'),
        ('contact_phone', 'phone'),
        ('contact_wechat', 'wechat'),
        ('contact_qq', 'qq'),
    )
    contacts = []
    for event in UniversityEvent.objects.all().iterator():
        verified_at = event.created_at or django.utils.timezone.now()
        for field_name, channel in field_channels:
            value = (getattr(event, field_name, '') or '').strip()
            if not value:
                continue
            contacts.append(ContactPoint(
                university_event_id=event.id,
                channel=channel,
                value=value,
                purpose='event',
                evidence_url=event.source_url,
                first_verified_at=verified_at,
                last_verified_at=verified_at,
                confidence=0,
                verification_status='unverified',
                is_public_business_contact=False,
                is_mock=False,
            ))
    ContactPoint.objects.bulk_create(contacts, ignore_conflicts=True, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_add_tweet_space_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='运行 ID')),
                ('task_type', models.CharField(max_length=40, verbose_name='Agent 任务类型')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('fallback', 'Deterministic fallback'), ('blocked', 'Privacy blocked')], default='queued', max_length=20, verbose_name='状态')),
                ('model_provider', models.CharField(blank=True, default='', max_length=80, verbose_name='模型 Provider')),
                ('model_name', models.CharField(blank=True, default='', max_length=120, verbose_name='模型名称')),
                ('model_version', models.CharField(max_length=120, verbose_name='模型/规则版本')),
                ('schema_name', models.CharField(max_length=120, verbose_name='Schema 名称')),
                ('schema_version', models.CharField(max_length=80, verbose_name='Schema 版本')),
                ('prompt_version', models.CharField(blank=True, default='', max_length=80, verbose_name='Prompt 版本')),
                ('input_references', models.JSONField(default=list, verbose_name='输入引用')),
                ('citations', models.JSONField(blank=True, default=list, verbose_name='输出引用')),
                ('input_snapshot', models.JSONField(blank=True, default=dict, verbose_name='脱敏输入快照')),
                ('structured_output', models.JSONField(blank=True, default=dict, verbose_name='脱敏结构化输出')),
                ('tool_calls', models.JSONField(blank=True, default=list, verbose_name='脱敏工具调用')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='输入 token')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='输出 token')),
                ('cached_input_tokens', models.PositiveIntegerField(default=0, verbose_name='缓存输入 token')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='延迟毫秒')),
                ('cost_microusd', models.PositiveBigIntegerField(default=0, verbose_name='成本 (micro USD)')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('cache_hit', models.BooleanField(default=False, verbose_name='缓存命中')),
                ('privacy_status', models.CharField(choices=[('no_pii', 'No PII present'), ('redacted', 'Sensitive fields redacted'), ('blocked', 'Blocked by privacy guard')], default='no_pii', max_length=20, verbose_name='隐私状态')),
                ('redacted_fields', models.JSONField(blank=True, default=list, verbose_name='脱敏字段')),
                ('error_code', models.CharField(blank=True, default='', max_length=120, verbose_name='错误码')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='脱敏错误摘要')),
                ('human_feedback', models.JSONField(blank=True, default=dict, verbose_name='人工反馈')),
                ('feedback_by', models.CharField(blank=True, default='', max_length=120, verbose_name='反馈人')),
                ('feedback_at', models.DateTimeField(blank=True, null=True, verbose_name='反馈时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='home.workspace', verbose_name='工作区')),
            ],
            options={
                'verbose_name': 'Agent 运行',
                'verbose_name_plural': 'Agent 运行',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_key', models.CharField(max_length=120, verbose_name='Campaign 标识')),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('verified', 'Human verified'), ('rejected', 'Rejected')], default='suggested', max_length=20, verbose_name='状态')),
                ('overall_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='总分')),
                ('theme_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='主题分')),
                ('audience_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='受众分')),
                ('timing_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='时间分')),
                ('city_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='城市分')),
                ('resource_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='资源分')),
                ('information_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='信息完整度分')),
                ('fit_points', models.JSONField(blank=True, default=list, verbose_name='契合点')),
                ('missing_information', models.JSONField(blank=True, default=list, verbose_name='缺失信息')),
                ('conflicts', models.JSONField(blank=True, default=list, verbose_name='冲突项')),
                ('citations', models.JSONField(default=list, verbose_name='证据引用')),
                ('score_citations', models.JSONField(default=dict, verbose_name='分项评分引用')),
                ('scoring_version', models.CharField(max_length=80, verbose_name='评分规则版本')),
                ('model_version', models.CharField(max_length=120, verbose_name='模型/规则版本')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=120, verbose_name='审核人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_matches', to='home.universityevent', verbose_name='高校活动')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_matches', to='home.workspace', verbose_name='工作区')),
            ],
            options={
                'verbose_name': '合作匹配',
                'verbose_name_plural': '合作匹配',
                'ordering': ['-overall_score', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('contact_page', 'Public contact page'), ('phone', 'Phone'), ('wechat', 'WeChat'), ('qq', 'QQ')], max_length=30, verbose_name='联系方式类型')),
                ('value', models.CharField(max_length=500, verbose_name='联系值')),
                ('purpose', models.CharField(choices=[('event', 'Event coordination'), ('collaboration', 'Collaboration'), ('media', 'Media'), ('general', 'General public enquiry')], max_length=30, verbose_name='用途')),
                ('evidence_url', models.URLField(max_length=800, verbose_name='公开证据 URL')),
                ('first_verified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次核验时间')),
                ('last_verified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近核验时间')),
                ('confidence', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='可信度 (0-100)')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified public business contact'), ('stale', 'Stale / needs re-verification'), ('opted_out', 'Opted out'), ('suppressed', 'Suppressed')], default='unverified', max_length=20, verbose_name='核验/退订状态')),
                ('is_public_business_contact', models.BooleanField(default=False, verbose_name='公开机构/活动联系方式')),
                ('is_mock', models.BooleanField(default=False, verbose_name='演示联系人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('university_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_points', to='home.universityevent', verbose_name='关联活动')),
            ],
            options={
                'verbose_name': '活动公开联系点',
                'verbose_name_plural': '活动公开联系点',
                'ordering': ['university_event', 'channel', 'value'],
            },
        ),
        migrations.CreateModel(
            name='OutreachBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='批次名称')),
                ('selection_criteria', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('target_count', models.PositiveIntegerField(default=0, verbose_name='目标数量')),
                ('rate_limit_per_hour', models.PositiveIntegerField(default=10, verbose_name='每小时上限')),
                ('daily_limit', models.PositiveIntegerField(default=30, verbose_name='每日上限')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='draft', max_length=24, verbose_name='状态')),
                ('created_by', models.CharField(max_length=120, verbose_name='创建人')),
                ('approved_by', models.CharField(blank=True, default='', max_length=120, verbose_name='审批人')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='计划发送时间')),
                ('stop_requested', models.BooleanField(default=False, verbose_name='立即停止')),
                ('stop_reason', models.TextField(blank=True, default='', verbose_name='停止原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_batches', to='home.workspace', verbose_name='工作区')),
            ],
            options={
                'verbose_name': '外联批次',
                'verbose_name_plural': '外联批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='draft', max_length=24, verbose_name='审批状态')),
                ('packages', models.JSONField(default=list, verbose_name='轻/中/深三档合作包')),
                ('partner_value', models.TextField(blank=True, default='', verbose_name='合作方价值')),
                ('workspace_value', models.TextField(blank=True, default='', verbose_name='工作区价值')),
                ('resources', models.JSONField(blank=True, default=list, verbose_name='资源清单')),
                ('pending_questions', models.JSONField(blank=True, default=list, verbose_name='待确认项')),
                ('risks', models.JSONField(blank=True, default=list, verbose_name='风险')),
                ('source_refs', models.JSONField(default=list, verbose_name='事实来源引用')),
                ('evidence', models.JSONField(default=list, verbose_name='结论与引用映射')),
                ('guardrail_checks', models.JSONField(default=dict, verbose_name='合规检查')),
                ('edit_summary', models.TextField(blank=True, default='', verbose_name='人工编辑摘要')),
                ('edited_by', models.CharField(blank=True, default='', max_length=120, verbose_name='编辑人')),
                ('approved_by', models.CharField(blank=True, default='', max_length=120, verbose_name='审批人')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='驳回原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='home.collaborationmatch', verbose_name='合作匹配')),
                ('previous_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_version', to='home.proposal', verbose_name='上一版本')),
            ],
            options={
                'verbose_name': '合作提案',
                'verbose_name_plural': '合作提案',
                'ordering': ['match', '-version'],
            },
        ),
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_key', models.CharField(editable=False, max_length=240, verbose_name='规范化高校幂等键')),
                ('proposal_version', models.PositiveIntegerField(verbose_name='提案版本快照')),
                ('contact_evidence_url', models.URLField(max_length=800, verbose_name='联系证据 URL 快照')),
                ('contact_verified_at', models.DateTimeField(verbose_name='联系证据核验时间快照')),
                ('idempotency_key', models.CharField(max_length=160, unique=True, verbose_name='发送幂等键')),
                ('subject', models.CharField(max_length=300, verbose_name='主题')),
                ('body', models.TextField(verbose_name='个性化正文')),
                ('personalization', models.JSONField(blank=True, default=list, verbose_name='个性化依据')),
                ('citation_ids', models.JSONField(default=list, verbose_name='事实引用')),
                ('guardrail_checks', models.JSONField(default=dict, verbose_name='外联合规检查')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting approval'), ('approved', 'Approved'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('unsubscribed', 'Unsubscribed'), ('suppressed', 'Suppressed'), ('cancelled', 'Cancelled')], default='draft', max_length=24, verbose_name='状态')),
                ('approved_by', models.CharField(blank=True, default='', max_length=120, verbose_name='审批人')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('provider', models.CharField(blank=True, default='', max_length=80, verbose_name='Provider')),
                ('provider_status', models.CharField(choices=[('none', 'Not submitted'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('delivered', 'Delivered'), ('deferred', 'Deferred'), ('bounced', 'Bounced'), ('rejected', 'Rejected'), ('complained', 'Complaint'), ('unsubscribed', 'Unsubscribed')], default='none', max_length=24, verbose_name='Provider 状态')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Provider 消息 ID')),
                ('provider_error_code', models.CharField(blank=True, default='', max_length=120, verbose_name='Provider 错误码')),
                ('provider_error_message', models.TextField(blank=True, default='', verbose_name='Provider 错误摘要')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='重试次数')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('bounced_at', models.DateTimeField(blank=True, null=True, verbose_name='退信时间')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='退订时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='home.outreachbatch', verbose_name='外联批次')),
                ('contact_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_messages', to='home.contactpoint', verbose_name='联系证据')),
                ('university_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_messages', to='home.universityevent', verbose_name='目标高校活动')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_messages', to='home.proposal', verbose_name='提案')),
            ],
            options={
                'verbose_name': '外联消息',
                'verbose_name_plural': '外联消息',
                'ordering': ['batch', 'university_event'],
            },
        ),
        migrations.RunPython(backfill_legacy_event_contacts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='collaborationmatch',
            constraint=models.UniqueConstraint(fields=('workspace', 'event', 'campaign_key', 'scoring_version'), name='unique_workspace_event_campaign_scoring'),
        ),
        migrations.AddConstraint(
            model_name='contactpoint',
            constraint=models.UniqueConstraint(fields=('university_event', 'channel', 'value'), name='unique_event_contact_channel_value'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('match', 'version'), name='unique_match_proposal_version'),
        ),
        migrations.AddConstraint(
            model_name='outreachmessage',
            constraint=models.UniqueConstraint(fields=('batch', 'university_key'), name='unique_batch_university_message'),
        ),
    ]
