# Generated by Django 4.2.30 on 2026-07-10 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_data_growth_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityevent',
            name='completeness_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='confidence_explanation',
            field=models.JSONField(blank=True, default=dict, verbose_name='可信度解释'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='date_conflict',
            field=models.BooleanField(default=False, verbose_name='日期是否冲突'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='date_conflict_note',
            field=models.TextField(blank=True, default='', verbose_name='日期冲突证据'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='date_consistency_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='event_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='活动状态'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='freshness_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='freshness_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('fresh', 'Fresh'), ('aging', 'Aging'), ('stale', 'Stale')], default='unknown', max_length=20, verbose_name='页面新鲜度'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='officiality_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='page_last_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='来源页最近核验时间'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='page_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='来源页发布时间'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='postponement_note',
            field=models.TextField(blank=True, default='', verbose_name='延期/取消说明'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='registration_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('open', 'Open'), ('waitlist', 'Waitlist'), ('closed', 'Closed'), ('not_required', 'Not required')], default='unknown', max_length=20, verbose_name='报名状态'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='source_tier',
            field=models.CharField(choices=[('official_university', 'University official site'), ('official_department', 'Faculty / innovation center'), ('public_organization', 'Public student organization / society'), ('event_platform', 'Public event platform'), ('unknown', 'Unknown source')], default='unknown', max_length=30, verbose_name='来源等级'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='timezone_name',
            field=models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='活动时区'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='verification_note',
            field=models.TextField(blank=True, default='', verbose_name='核验备注'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='verification_queue_reasons',
            field=models.JSONField(blank=True, default=list, verbose_name='人工核验原因'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='进入核验队列时间'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending human verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='活动核验状态'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='核验时间'),
        ),
        migrations.AddField(
            model_name='universityevent',
            name='verified_by',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='核验人'),
        ),
    ]
