# Generated by Django 4.2.30 on 2026-07-10 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_universityevent_completeness_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAgentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='预算日期')),
                ('limit_microusd', models.PositiveBigIntegerField(default=0, verbose_name='预算上限 (micro USD)')),
                ('spent_microusd', models.PositiveBigIntegerField(default=0, verbose_name='已用成本 (micro USD)')),
                ('request_limit', models.PositiveIntegerField(default=0, verbose_name='请求上限，0 表示不限')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='已用请求数')),
                ('fallback_only', models.BooleanField(default=False, verbose_name='仅允许确定性降级')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_budgets', to='home.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_key', models.CharField(max_length=180, verbose_name='告警幂等键')),
                ('alert_type', models.CharField(max_length=80, verbose_name='告警类型')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('summary', models.CharField(max_length=300, verbose_name='脱敏摘要')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='聚合指标证据')),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_alerts', to='home.sourceconnector')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_alerts', to='home.workspace')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyagentbudget',
            constraint=models.UniqueConstraint(fields=('workspace', 'date'), name='unique_workspace_agent_budget_date'),
        ),
        migrations.AddConstraint(
            model_name='agentalert',
            constraint=models.UniqueConstraint(fields=('workspace', 'alert_key'), name='unique_workspace_agent_alert_key'),
        ),
    ]
