# Generated by Django 4.2.30 on 2026-07-11 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_agentrun_nullable_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=180, verbose_name='稳定 Claim ID')),
                ('subject_type', models.CharField(max_length=40, verbose_name='主体类型')),
                ('subject_id', models.CharField(max_length=180, verbose_name='主体 ID')),
                ('predicate', models.CharField(max_length=120, verbose_name='关系/字段')),
                ('value', models.JSONField(verbose_name='结构化事实值')),
                ('quote', models.TextField(verbose_name='原文片段')),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('conflict', 'Conflict'), ('expired', 'Expired'), ('unknown', 'Unknown')], default='verified', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject_type', 'subject_id', 'predicate'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=180, verbose_name='稳定来源 ID')),
                ('source_type', models.CharField(choices=[('event', 'Event record'), ('capability', 'Approved capability'), ('official_web', 'Official web page'), ('public_web', 'Public web page')], max_length=24, verbose_name='来源类型')),
                ('title', models.CharField(max_length=500, verbose_name='来源标题')),
                ('url', models.URLField(blank=True, default='', max_length=1000, verbose_name='公开来源 URL')),
                ('domain', models.CharField(blank=True, default='', max_length=255, verbose_name='来源域名')),
                ('is_official', models.BooleanField(default=False, verbose_name='是否官方来源')),
                ('authority_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('content_hash', models.CharField(max_length=64, verbose_name='正文指纹')),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='核验时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='安全来源元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_sources', to='home.workspace', verbose_name='工作区')),
            ],
            options={
                'ordering': ['-authority_score', '-retrieved_at'],
            },
        ),
        migrations.CreateModel(
            name='WebResearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_url', models.URLField(max_length=1000)),
                ('final_url', models.URLField(blank=True, default='', max_length=1000)),
                ('domain', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected')], max_length=20)),
                ('official_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('content_bytes', models.PositiveIntegerField(default=0)),
                ('body_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('injection_flags', models.JSONField(blank=True, default=list)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=160)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_document', to='home.evidencesource')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_documents', to='home.workspace')),
            ],
            options={
                'ordering': ['-official_score', '-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('schema_version', models.CharField(default='opportunity-v1', max_length=80)),
                ('hypothesis', models.TextField()),
                ('target_audiences', models.JSONField(default=list)),
                ('missing_facts', models.JSONField(default=list)),
                ('success_metrics', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('model_version', models.CharField(default='deterministic-opportunity-v1', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter_claims', models.ManyToManyField(related_name='challenged_opportunities', to='home.evidenceclaim')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='home.universityevent')),
                ('supporting_claims', models.ManyToManyField(related_name='supported_opportunities', to='home.evidenceclaim')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='home.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_kind', models.CharField(max_length=40)),
                ('from_id', models.CharField(max_length=180)),
                ('relation_type', models.CharField(max_length=80)),
                ('to_kind', models.CharField(max_length=40)),
                ('to_id', models.CharField(max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('via_claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='home.evidenceclaim', verbose_name='关系证据')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_relations', to='home.workspace', verbose_name='工作区')),
            ],
        ),
        migrations.AddField(
            model_name='evidenceclaim',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='home.evidencesource', verbose_name='原始来源'),
        ),
        migrations.AddField(
            model_name='evidenceclaim',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_claims', to='home.workspace', verbose_name='工作区'),
        ),
        migrations.AddConstraint(
            model_name='evidencesource',
            constraint=models.UniqueConstraint(fields=('workspace', 'source_id'), name='unique_workspace_evidence_source_id'),
        ),
        migrations.AddIndex(
            model_name='evidencerelation',
            index=models.Index(fields=['workspace', 'from_kind', 'from_id'], name='evidence_from_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerelation',
            index=models.Index(fields=['workspace', 'to_kind', 'to_id'], name='evidence_to_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencerelation',
            constraint=models.UniqueConstraint(fields=('workspace', 'from_kind', 'from_id', 'relation_type', 'to_kind', 'to_id', 'via_claim'), name='unique_evidence_relation_edge'),
        ),
        migrations.AddIndex(
            model_name='evidenceclaim',
            index=models.Index(fields=['workspace', 'subject_type', 'subject_id'], name='evidence_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='evidenceclaim',
            index=models.Index(fields=['workspace', 'status'], name='evidence_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidenceclaim',
            constraint=models.UniqueConstraint(fields=('workspace', 'claim_id'), name='unique_workspace_evidence_claim_id'),
        ),
    ]
